_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 50
                - 55
                - 105
            "2":
                - 1
                - 50
                - 55
                - 105
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
paths:
    value:
        data: ../../data/processed
        figures: ../../reports
        model: ../../models
train:
    value:
        batch_size: 64
        epochs: 10
        lr: 0.001
